name: Test Local Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  local-deploy-k8s:
    name: Local Deploy (Kubernetes)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Intall CLI
        run: az bicep install

      - name: Start minikube
        uses: medyagh/setup-minikube@latest

      - name: Run "echo-server"
        env:
          BICEP_TRACING_ENABLED: true
        run: ~/.azure/bin/bicep local-deploy samples/e2e/echo-server-e2e.bicepparam

      - name: Wait for endpoint
        run: |
          kubectl wait --for=condition=ready pod -l app=echo-server --timeout=60s

      - name: Kubectl outputs
        run: |
          kubectl describe service
          kubectl describe deployment
          kubectl describe pod