name: Publish Providers

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  CI: true
  PROVIDERS_REGISTRY_NAME: biceplocaldeploy

jobs:
  deploy-acr:
    name: Deploy ACR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
          submodules: true

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PROVIDERS_CLIENT_ID }}
          tenant-id: ${{ secrets.PROVIDERS_TENANT_ID }}
          subscription-id: ${{ secrets.PROVIDERS_SUBSCRIPTION_ID }}

      - name: Deploy
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az deployment group create \
              --resource-group ${{ env.PROVIDERS_REGISTRY_NAME }} \
              --parameters ./infra/main.bicepparam

  publish-providers:
    name: Publish ${{ matrix.provider.name }} Provider
    runs-on: ubuntu-latest

    strategy:
      matrix:
        provider:
          - name: Github
            publish-script: src/Bicep.Extension.Github/publish.sh
          - name: Kubernetes
            publish-script: src/Bicep.Extension.Kubernetes/publish.sh
          - name: Utils
            publish-script: src/Bicep.Extension.Utils/publish.sh

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
          submodules: true

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PROVIDERS_CLIENT_ID }}
          tenant-id: ${{ secrets.PROVIDERS_TENANT_ID }}
          subscription-id: ${{ secrets.PROVIDERS_SUBSCRIPTION_ID }}
  
      - name: Intall CLI
        env:
          GH_TOKEN: ${{ github.token }}
        run: bash <(curl -Ls https://aka.ms/bicep/nightly-cli.sh) --repo anthony-c-martin/bicep --branch rpc
      
      - name: Run nbgv
        id: nbgv
        uses: dotnet/nbgv@v0.4.2
        
      - name: Publish Provider
        run: bash ${{ matrix.provider.publish-script }} ${{ env.PROVIDERS_REGISTRY_NAME }} ${{ steps.nbgv.outputs.SimpleVersion }}