name: Publish Extensions

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  CI: true
  EXTENSIONS_REGISTRY_NAME: biceplocaldeploy

jobs:
  deploy-acr:
    name: Deploy ACR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
          submodules: true

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.EXTENSIONS_CLIENT_ID }}
          tenant-id: ${{ secrets.EXTENSIONS_TENANT_ID }}
          subscription-id: ${{ secrets.EXTENSIONS_SUBSCRIPTION_ID }}

      - name: Deploy
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az deployment group create \
              --resource-group ${{ env.EXTENSIONS_REGISTRY_NAME }} \
              --parameters ./infra/main.bicepparam

  publish-extensions:
    name: Publish ${{ matrix.extension.name }} Extension
    runs-on: ubuntu-latest

    strategy:
      matrix:
        extension:
          - name: Github
            publish-script: src/github/publish.sh
            repo-path: extensions/github
          - name: Kubernetes
            publish-script: src/kubernetes/publish.sh
            repo-path: extensions/kubernetes
          - name: Utils
            publish-script: src/utils/publish.sh
            repo-path: extensions/utils
          - name: Http
            publish-script: src/http/publish.sh
            repo-path: extensions/http

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
          submodules: true

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.EXTENSIONS_CLIENT_ID }}
          tenant-id: ${{ secrets.EXTENSIONS_TENANT_ID }}
          subscription-id: ${{ secrets.EXTENSIONS_SUBSCRIPTION_ID }}
  
      - name: Intall CLI
        run: az bicep install --version v0.29.47
      
      - name: Run nbgv
        id: nbgv
        uses: dotnet/nbgv@v0.4.2
        
      - name: Publish Extension
        run: |
          target="br:${{ env.EXTENSIONS_REGISTRY_NAME }}.azurecr.io/${{ matrix.extension.repo-path }}:${{ steps.nbgv.outputs.SimpleVersion }}"
          bash ${{ matrix.extension.publish-script }} $target

          echo "Published extension \`$target\`." >> $GITHUB_STEP_SUMMARY